In [1]:
import pandas as pd
import numpy as np
import ast

## Players table

In [76]:
players = pd.read_csv('players.csv')
players

,tag,name,nameColor,trophies,highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,duoVictories,bestRoboRumbleTime,bestTimeAsBigBrawler,brawlers,icon.id,player_tag,club.tag,club.name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,296,2,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 8...",28000164,#9ULJPY8LV,NaN,NaN
1,#GYVL22U2V,kayler123,0xff1ba5f5,3352,3352,29,5016,0,289,20,77,0,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 1...",28000807,#GYVL22U2V,#J9PLCRUG,ANGRY SQUAD
2,#LGLJCPVYG,ewok,0xffa8e132,2092,2093,24,3513,0,146,29,68,1,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 5...",28000002,#LGLJCPVYG,#22RUQCRJJ,Edgar's Club
3,#PG2CCG89U,YaSsi3N,0xffa8e132,22645,22645,135,94775,0,3658,609,704,7,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 9...",28000222,#PG2CCG89U,#V9VPYRV8,Good Team🔥
4,#RPGJRPLP,TYB,0xff1ba5f5,2240,2242,39,8909,0,307,63,27,0,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 7...",28000447,#RPGJRPLP,#GVRYUY9,FLEX TAPE
5,#GVOVYGPO,Lexiphea,0xffcb5aff,44790,44792,212,231573,0,12350,430,1839,5,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 1...",28000170,#GVOVYGPO,#RL80U0VP,All stars
6,#9U2JV2ORP,사냥의시작이야,0xff4ddba2,40146,40222,156,125899,0,7097,870,369,5,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 1...",28000132,#9U2JV2ORP,#2VR8GVGRV,Tkメ
7,#9VYO9LPO,[Бан]#LOVE,0xffa8e132,24281,24513,117,72462,0,1945,690,298,5,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 9...",28000059,#9VYO9LPO,#2R0CCL9JJ,☘️PaPoRoTnIk☘️
8,#VYO89R8P,melson,0xffa2e3fe,20841,20845,113,67001,0,2229,129,1231,9,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 1...",28000009,#VYO89R8P,#20RY89JGV,🩲爱好者
9,#YOR2CO2R2,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,79,304,5,0,"[{'id': 16000000, 'name': 'SHELLY', 'power': 7...",28000066,#YOR2CO2R2,#2Y9GV8GG9,idk

In [77]:
# editing player_tag from O to 0
players['tag'] = players['tag'].replace('O', '0', regex=True)
players['tag'].unique()

array(['#9ULJPY8LV', '#GYVL22U2V', '#LGLJCPVYG', '#PG2CCG89U',
       '#RPGJRPLP', '#GV0VYGP0', '#9U2JV20RP', '#9VY09LP0', '#VY089R8P',
       '#Y0R2C02R2'], dtype=object)

In [78]:
# cleaning 'brawlers' column

# 1. Parse the 'brawlers' column from string to list of dicts
players['brawlers'] = players['brawlers'].apply(ast.literal_eval)

# 2. Expand brawlers: 1 row per brawler, with player info repeated
players_expanded = players.explode('brawlers').reset_index(drop=True)

# 3. Normalize the 'brawlers' dictionaries into separate columns
brawlers_df = pd.json_normalize(players_expanded['brawlers'])

# 4. Drop the old 'brawlers' column and combine with the flattened brawler info
players_expanded_clean = pd.concat([players_expanded.drop(columns=['brawlers']), brawlers_df], axis=1)

players_expanded_clean.head(10)

,tag,name,nameColor,trophies,highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,club.name,id,name,power,rank,trophies,highestTrophies,gears,starPowers,gadgets
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000000,SHELLY,8,16,305,305,"[{'id': 62000002, 'name': 'DAMAGE', 'level': 3}]",[],"[{'id': 23000288, 'name': 'CLAY PIGEONS'}, {'i..."
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000001,COLT,8,19,372,372,[],[],"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id..."
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000002,BULL,8,15,281,281,[],[],[]
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000003,BROCK,8,19,360,364,[],[],[]
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000004,RICO,7,13,246,246,[],[],"[{'id': 23000409, 'name': 'BOUNCY CASTLE'}]"
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000006,BARLEY,8,13,250,252,[],[],"[{'id': 23000293, 'name': 'HERBAL TONIC'}, {'i..."
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000007,JESSIE,8,26,489,505,[],[],"[{'id': 23000295, 'name': 'RECOIL SPRING'}, {'..."
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000008,NITA,8,18,342,342,[],[],"[{'id': 23000249, 'name': 'BEAR PAWS'}, {'id':..."
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000009,DYNAMIKE,9,13,237,240,[],[],[]
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000010,EL PRIMO,8,23,448,452,[],[],"[{'id': 23000264, 'name': 'SUPLEX SUPPLEMENT'}..."

In [79]:
# Rename 'name' column
players_expanded_clean.columns = [
    'player_name' if i == 1 else 'brawler_name' if col == 'name' and i > 2 else col
    for i, col in enumerate(players_expanded_clean.columns)
]

In [80]:
# Rename 'id' column
players_expanded_clean.rename(columns={'id': 'brawler_id'}, inplace=True)

In [81]:
# renaming 'trophies' column
players_expanded_clean.columns = [
    'player_trophies' if i == 3 else 'brawler_trophies' if col == 'trophies' and i > 3 else col
    for i, col in enumerate(players_expanded_clean.columns)
]
players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,club.name,brawler_id,brawler_name,power,rank,brawler_trophies,highestTrophies,gears,starPowers,gadgets
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000000,SHELLY,8,16,305,305,"[{'id': 62000002, 'name': 'DAMAGE', 'level': 3}]",[],"[{'id': 23000288, 'name': 'CLAY PIGEONS'}, {'i..."
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000001,COLT,8,19,372,372,[],[],"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id..."
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000002,BULL,8,15,281,281,[],[],[]
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000003,BROCK,8,19,360,364,[],[],[]
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000004,RICO,7,13,246,246,[],[],"[{'id': 23000409, 'name': 'BOUNCY CASTLE'}]"
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000006,BARLEY,8,13,250,252,[],[],"[{'id': 23000293, 'name': 'HERBAL TONIC'}, {'i..."
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000007,JESSIE,8,26,489,505,[],[],"[{'id': 23000295, 'name': 'RECOIL SPRING'}, {'..."
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000008,NITA,8,18,342,342,[],[],"[{'id': 23000249, 'name': 'BEAR PAWS'}, {'id':..."
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000009,DYNAMIKE,9,13,237,240,[],[],[]
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000010,EL PRIMO,8,23,448,452,[],[],"[{'id': 23000264, 'name': 'SUPLEX SUPPLEMENT'}..."

In [82]:
# renaming 'highestTrophies' column
players_expanded_clean.columns = [
    'player_highestTrophies' if i == 4 else 'brawler_highestTrophies' if col == 'highestTrophies' and i > 4 else col
    for i, col in enumerate(players_expanded_clean.columns)
]
players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,club.name,brawler_id,brawler_name,power,rank,brawler_trophies,brawler_highestTrophies,gears,starPowers,gadgets
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000000,SHELLY,8,16,305,305,"[{'id': 62000002, 'name': 'DAMAGE', 'level': 3}]",[],"[{'id': 23000288, 'name': 'CLAY PIGEONS'}, {'i..."
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000001,COLT,8,19,372,372,[],[],"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id..."
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000002,BULL,8,15,281,281,[],[],[]
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000003,BROCK,8,19,360,364,[],[],[]
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000004,RICO,7,13,246,246,[],[],"[{'id': 23000409, 'name': 'BOUNCY CASTLE'}]"
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000006,BARLEY,8,13,250,252,[],[],"[{'id': 23000293, 'name': 'HERBAL TONIC'}, {'i..."
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000007,JESSIE,8,26,489,505,[],[],"[{'id': 23000295, 'name': 'RECOIL SPRING'}, {'..."
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000008,NITA,8,18,342,342,[],[],"[{'id': 23000249, 'name': 'BEAR PAWS'}, {'id':..."
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000009,DYNAMIKE,9,13,237,240,[],[],[]
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NaN,16000010,EL PRIMO,8,23,448,452,[],[],"[{'id': 23000264, 'name': 'SUPLEX SUPPLEMENT'}..."

In [83]:
# Cleaning the 'gears' column

# 1. Parse the 'gears' column from string to list of dicts
def safe_eval(val):
    if isinstance(val, str):
        try:
            return ast.literal_eval(val)
        except (ValueError, SyntaxError):
            return []
    elif isinstance(val, list):
        return val
    else:
        return []

players_expanded_clean['gears'] = players_expanded_clean['gears'].apply(safe_eval)

# 2. Expand gears: 1 row per gear per brawler, with player info repeated
players_expanded_clean = players_expanded_clean.explode('gears').reset_index(drop=True)

# 3. Normalize the 'gears' dictionaries into separate columns
gears_df = pd.json_normalize(players_expanded_clean['gears'])

# 4. Drop the old 'gears' column and combine with the flattened gear info
players_expanded_clean = pd.concat([players_expanded_clean.drop(columns=['gears']), gears_df], axis=1)

players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,brawler_name,power,rank,brawler_trophies,brawler_highestTrophies,starPowers,gadgets,id,name,level
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,SHELLY,8,16,305,305,[],"[{'id': 23000288, 'name': 'CLAY PIGEONS'}, {'i...",62000002.0,DAMAGE,3.0
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,COLT,8,19,372,372,[],"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id...",NaN,NaN,NaN
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,BULL,8,15,281,281,[],[],NaN,NaN,NaN
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,BROCK,8,19,360,364,[],[],NaN,NaN,NaN
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,RICO,7,13,246,246,[],"[{'id': 23000409, 'name': 'BOUNCY CASTLE'}]",NaN,NaN,NaN
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,BARLEY,8,13,250,252,[],"[{'id': 23000293, 'name': 'HERBAL TONIC'}, {'i...",NaN,NaN,NaN
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,JESSIE,8,26,489,505,[],"[{'id': 23000295, 'name': 'RECOIL SPRING'}, {'...",NaN,NaN,NaN
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,NITA,8,18,342,342,[],"[{'id': 23000249, 'name': 'BEAR PAWS'}, {'id':...",NaN,NaN,NaN
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,DYNAMIKE,9,13,237,240,[],[],NaN,NaN,NaN
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,EL PRIMO,8,23,448,452,[],"[{'id': 23000264, 'name': 'SUPLEX SUPPLEMENT'}...",NaN,NaN,NaN

In [84]:
# rename 'id' 'name' 'level' columns
players_expanded_clean.rename(columns={'id': 'gear_id', 'name': 'gear_name', 'level': 'gear_level'}, inplace=True)

In [85]:
# Cleaning the 'gadgets' column

# 1. Parse the 'gears' column from string to list of dicts
def safe_eval(val):
    if isinstance(val, str):
        try:
            return ast.literal_eval(val)
        except (ValueError, SyntaxError):
            return []
    elif isinstance(val, list):
        return val
    else:
        return []

players_expanded_clean['gadgets'] = players_expanded_clean['gadgets'].apply(safe_eval)

# 2. Expand gadget: 1 row per gadget per brawler, with player info repeated
players_expanded_clean = players_expanded_clean.explode('gadgets').reset_index(drop=True)

# 3. Normalize the 'gadget' dictionaries into separate columns
gadgets_df = pd.json_normalize(players_expanded_clean['gadgets'])

# 4. Drop the old 'gadget' column and combine with the flattened gadget info
players_expanded_clean = pd.concat([players_expanded_clean.drop(columns=['gadgets']), gadgets_df], axis=1)

players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,power,rank,brawler_trophies,brawler_highestTrophies,starPowers,gear_id,gear_name,gear_level,id,name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,16,305,305,[],62000002.0,DAMAGE,3.0,23000288.0,CLAY PIGEONS
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,16,305,305,[],62000002.0,DAMAGE,3.0,23000255.0,FAST FORWARD
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,19,372,372,[],NaN,NaN,NaN,23000273.0,SPEEDLOADER
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,19,372,372,[],NaN,NaN,NaN,23000319.0,SILVER BULLET
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,15,281,281,[],NaN,NaN,NaN,NaN,NaN
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,19,360,364,[],NaN,NaN,NaN,NaN,NaN
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,7,13,246,246,[],NaN,NaN,NaN,23000409.0,BOUNCY CASTLE
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,13,250,252,[],NaN,NaN,NaN,23000293.0,HERBAL TONIC
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,13,250,252,[],NaN,NaN,NaN,23000250.0,STICKY SYRUP MIXER
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,8,26,489,505,[],NaN,NaN,NaN,23000295.0,RECOIL SPRING

In [86]:
# rename 'id' 'name' columns
players_expanded_clean.rename(columns={'id': 'gadget_id', 'name': 'gadget_name'}, inplace=True)

In [87]:
# Cleaning the 'starPowers' column

# 1. Parse the 'starPowers' column from string to list of dicts
def safe_eval(val):
    if isinstance(val, str):
        try:
            return ast.literal_eval(val)
        except (ValueError, SyntaxError):
            return []
    elif isinstance(val, list):
        return val
    else:
        return []

players_expanded_clean['starPowers'] = players_expanded_clean['starPowers'].apply(safe_eval)

# 2. Expand starPowers: 1 row per starPowers per brawler, with player info repeated
players_expanded_clean = players_expanded_clean.explode('starPowers').reset_index(drop=True)

# 3. Normalize the 'starPowers' dictionaries into separate columns
starPowers_df = pd.json_normalize(players_expanded_clean['starPowers'])

# 4. Drop the old 'starPowers' column and combine with the flattened starPowers info
players_expanded_clean = pd.concat([players_expanded_clean.drop(columns=['starPowers']), starPowers_df], axis=1)

players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,rank,brawler_trophies,brawler_highestTrophies,gear_id,gear_name,gear_level,gadget_id,gadget_name,id,name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000288.0,CLAY PIGEONS,NaN,NaN
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000255.0,FAST FORWARD,NaN,NaN
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000273.0,SPEEDLOADER,NaN,NaN
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000319.0,SILVER BULLET,NaN,NaN
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,15,281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,360,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,246,246,NaN,NaN,NaN,23000409.0,BOUNCY CASTLE,NaN,NaN
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000293.0,HERBAL TONIC,NaN,NaN
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000250.0,STICKY SYRUP MIXER,NaN,NaN
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,26,489,505,NaN,NaN,NaN,23000295.0,RECOIL SPRING,NaN,NaN

In [88]:
# rename 'id' 'name' columns
players_expanded_clean.rename(columns={'id': 'starPowers_id', 'name': 'starPowers_name'}, inplace=True)

In [89]:
players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,rank,brawler_trophies,brawler_highestTrophies,gear_id,gear_name,gear_level,gadget_id,gadget_name,starPowers_id,starPowers_name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000288.0,CLAY PIGEONS,NaN,NaN
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000255.0,FAST FORWARD,NaN,NaN
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000273.0,SPEEDLOADER,NaN,NaN
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000319.0,SILVER BULLET,NaN,NaN
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,15,281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,360,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,246,246,NaN,NaN,NaN,23000409.0,BOUNCY CASTLE,NaN,NaN
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000293.0,HERBAL TONIC,NaN,NaN
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000250.0,STICKY SYRUP MIXER,NaN,NaN
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,26,489,505,NaN,NaN,NaN,23000295.0,RECOIL SPRING,NaN,NaN

In [90]:
# Remove column 'player_tag' (duplication)
players_expanded_clean.drop(columns=['player_tag'], inplace=True)
players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,rank,brawler_trophies,brawler_highestTrophies,gear_id,gear_name,gear_level,gadget_id,gadget_name,starPowers_id,starPowers_name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000288.0,CLAY PIGEONS,NaN,NaN
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000255.0,FAST FORWARD,NaN,NaN
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000273.0,SPEEDLOADER,NaN,NaN
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000319.0,SILVER BULLET,NaN,NaN
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,15,281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,360,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,246,246,NaN,NaN,NaN,23000409.0,BOUNCY CASTLE,NaN,NaN
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000293.0,HERBAL TONIC,NaN,NaN
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000250.0,STICKY SYRUP MIXER,NaN,NaN
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,26,489,505,NaN,NaN,NaN,23000295.0,RECOIL SPRING,NaN,NaN

In [91]:
# renaming 'power' and 'rank' columns
players_expanded_clean.rename(columns={'power': 'brawler_power', 'rank': 'brawler_rank'}, inplace=True)
players_expanded_clean.head(10)

,tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,brawler_rank,brawler_trophies,brawler_highestTrophies,gear_id,gear_name,gear_level,gadget_id,gadget_name,starPowers_id,starPowers_name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000288.0,CLAY PIGEONS,NaN,NaN
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000255.0,FAST FORWARD,NaN,NaN
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000273.0,SPEEDLOADER,NaN,NaN
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000319.0,SILVER BULLET,NaN,NaN
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,15,281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,360,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,246,246,NaN,NaN,NaN,23000409.0,BOUNCY CASTLE,NaN,NaN
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000293.0,HERBAL TONIC,NaN,NaN
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000250.0,STICKY SYRUP MIXER,NaN,NaN
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,26,489,505,NaN,NaN,NaN,23000295.0,RECOIL SPRING,NaN,NaN

In [92]:
#5. Renaming 'tag' column
players_expanded_clean.rename(columns={'tag': 'player_tag'}, inplace=True)
players_expanded_clean.head(10)

,player_tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,brawler_rank,brawler_trophies,brawler_highestTrophies,gear_id,gear_name,gear_level,gadget_id,gadget_name,starPowers_id,starPowers_name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000288.0,CLAY PIGEONS,NaN,NaN
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000255.0,FAST FORWARD,NaN,NaN
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000273.0,SPEEDLOADER,NaN,NaN
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000319.0,SILVER BULLET,NaN,NaN
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,15,281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,360,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,246,246,NaN,NaN,NaN,23000409.0,BOUNCY CASTLE,NaN,NaN
7,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000293.0,HERBAL TONIC,NaN,NaN
8,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,13,250,252,NaN,NaN,NaN,23000250.0,STICKY SYRUP MIXER,NaN,NaN
9,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,26,489,505,NaN,NaN,NaN,23000295.0,RECOIL SPRING,NaN,NaN

In [93]:
players_expanded_clean

,player_tag,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,soloVictories,...,brawler_rank,brawler_trophies,brawler_highestTrophies,gear_id,gear_name,gear_level,gadget_id,gadget_name,starPowers_id,starPowers_name
0,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000288.0,CLAY PIGEONS,NaN,NaN
1,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,16,305,305,62000002.0,DAMAGE,3.0,23000255.0,FAST FORWARD,NaN,NaN
2,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000273.0,SPEEDLOADER,NaN,NaN
3,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,19,372,372,NaN,NaN,NaN,23000319.0,SILVER BULLET,NaN,NaN
4,#9ULJPY8LV,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,161,...,15,281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1344,#Y0R2C02R2,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,79,...,18,344,346,62000004.0,SHIELD,3.0,23000670.0,INTERLUDE,23000667.0,FAST BEATS
1345,#Y0R2C02R2,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,79,...,8,147,153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1346,#Y0R2C02R2,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,79,...,7,131,135,NaN,NaN,NaN,23000766.0,FRIENDSHIP IS GREAT,NaN,NaN
1347,#Y0R2C02R2,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,79,...,2,38,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1348,#Y0R2C02R2,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,79,...,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
# Step 1: Define the core brawler ID
core_cols = ['player_tag', 'brawler_name']

# Deduplicate the entire DataFrame just to be safe
players_expanded_clean = players_expanded_clean.drop_duplicates(subset=core_cols + ['gadget_id', 'starPowers_id'])

# ----------------------
# Gadgets
# ----------------------
# Drop NaNs, then deduplicate gadgets per player-brawler combo
gadget_df = players_expanded_clean.dropna(subset=['gadget_id']).copy()
gadget_df = gadget_df.drop_duplicates(subset=core_cols + ['gadget_id'])  # dedup gadget per brawler

# Number gadgets (after deduplication)
gadget_df['gadget_num'] = gadget_df.groupby(core_cols).cumcount() + 1
gadget_df = gadget_df[gadget_df['gadget_num'] <= 2]

# Pivot to wide format
gadget_wide = gadget_df.pivot(index=core_cols, columns='gadget_num', values='gadget_id')
gadget_wide.columns = [f'gadget_id_{int(col)}' for col in gadget_wide.columns]

# ----------------------
# Star Powers
# ----------------------
sp_df = players_expanded_clean.dropna(subset=['starPowers_id']).copy()
sp_df = sp_df.drop_duplicates(subset=core_cols + ['starPowers_id'])  # dedup star_power per brawler

sp_df['sp_num'] = sp_df.groupby(core_cols).cumcount() + 1
sp_df = sp_df[sp_df['sp_num'] <= 2]

sp_wide = sp_df.pivot(index=core_cols, columns='sp_num', values='starPowers_id')
sp_wide.columns = [f'starPowers_id_{int(col)}' for col in sp_wide.columns]

# ----------------------
# Merge with brawler base
# ----------------------
brawler_base = players_expanded_clean.drop_duplicates(subset=core_cols).set_index(core_cols)
final_df = brawler_base.drop(columns=['gadget_id', 'starPowers_id', 'gadget_name', 'starPowers_name'], errors='ignore') \
                       .join(gadget_wide, how='left') \
                       .join(sp_wide, how='left') \
                       .reset_index()

# Preview
final_df

,player_tag,brawler_name,player_name,nameColor,player_trophies,player_highestTrophies,expLevel,expPoints,isQualifiedFromChampionshipChallenge,3vs3Victories,...,brawler_rank,brawler_trophies,brawler_highestTrophies,gear_id,gear_name,gear_level,gadget_id_1,gadget_id_2,starPowers_id_1,starPowers_id_2
0,#9ULJPY8LV,SHELLY,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,...,16,305,305,62000002.0,DAMAGE,3.0,23000288.0,23000255.0,NaN,NaN
1,#9ULJPY8LV,COLT,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,...,19,372,372,NaN,NaN,NaN,23000273.0,23000319.0,NaN,NaN
2,#9ULJPY8LV,BULL,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,...,15,281,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,#9ULJPY8LV,BROCK,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,...,19,360,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,#9ULJPY8LV,RICO,CYX,0xffa2e3fe,10836,10856,64,22465,0,919,...,13,246,246,NaN,NaN,NaN,23000409.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,#Y0R2C02R2,MELODIE,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,...,18,344,346,62000002.0,DAMAGE,3.0,23000670.0,NaN,23000667.0,NaN
501,#Y0R2C02R2,ANGELO,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,...,8,147,153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,#Y0R2C02R2,BERRY,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,...,7,131,135,NaN,NaN,NaN,23000766.0,NaN,NaN,NaN
503,#Y0R2C02R2,CLANCY,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,...,2,38,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,#Y0R2C02R2,MEEPLE,bff123,0xff1ba5f5,14792,14826,87,40688,0,2183,...,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
# convert cleaned players df to csv
final_df.to_csv('cleaned_players.csv', index=False)

## Brawlers table

In [81]:
brawlers = pd.read_csv('brawlers.csv')
brawlers

,id,name,starPowers,gadgets
0,16000000,SHELLY,"[{'id': 23000076, 'name': 'SHELL SHOCK'}, {'id...","[{'id': 23000255, 'name': 'FAST FORWARD'}, {'i..."
1,16000001,COLT,"[{'id': 23000077, 'name': 'SLICK BOOTS'}, {'id...","[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id..."
2,16000002,BULL,"[{'id': 23000078, 'name': 'BERSERKER'}, {'id':...","[{'id': 23000272, 'name': 'T-BONE INJECTOR'}, ..."
3,16000003,BROCK,"[{'id': 23000079, 'name': 'MORE ROCKETS!'}, {'...","[{'id': 23000245, 'name': 'ROCKET LACES'}, {'i..."
4,16000004,RICO,"[{'id': 23000080, 'name': 'SUPER BOUNCY'}, {'i...","[{'id': 23000246, 'name': 'MULTIBALL LAUNCHER'..."
...,...,...,...,...
85,16000087,JUJU,"[{'id': 23000848, 'name': 'GUARDED GRIS-GRIS'}...","[{'id': 23000850, 'name': 'VOODOO CHILE'}, {'i..."
86,16000089,MEEPLE,"[{'id': 23000875, 'name': 'DO NOT PASS GO'}, {...","[{'id': 23000877, 'name': 'MANSIONS OF MEEPLE'..."
87,16000090,OLLIE,"[{'id': 23000883, 'name': 'KICK, PUSH'}, {'id'...","[{'id': 23000885, 'name': 'REGULATE'}, {'id': ..."
88,16000091,LUMI,"[{'id': 23000905, 'name': '42% BURNT'}, {'id':...","[{'id': 23000907, 'name': 'HIT THE LIGHTS'}, {..."
89,16000092,FINX,"[{'id': 23000915, 'name': 'HIEROGLYPH HALT'}, ...","[{'id': 23000917, 'name': 'BACK TO THE FINXTUR..."

In [82]:
# Cleaning the 'starPowers' column

# 1. Parse the 'starPowers' column from string to list of dicts
brawlers['starPowers'] = brawlers['starPowers'].apply(ast.literal_eval)

# 2. Expand starPowers: 1 row per starPower for each brawler
brawlers_expanded = brawlers.explode('starPowers').reset_index(drop=True)

# 3. Normalize the 'starPowers' dictionaries into separate columns
starPowers_df = pd.json_normalize(brawlers_expanded['starPowers'])

# 4. Drop the old 'starPowers' column and combine with the flattened starPower info
brawlers_expanded_clean = pd.concat([brawlers_expanded.drop(columns=['starPowers']), starPowers_df], axis=1)

brawlers_expanded_clean.head(10)

,id,name,gadgets,id,name
0,16000000,SHELLY,"[{'id': 23000255, 'name': 'FAST FORWARD'}, {'i...",23000076,SHELL SHOCK
1,16000000,SHELLY,"[{'id': 23000255, 'name': 'FAST FORWARD'}, {'i...",23000135,BAND-AID
2,16000001,COLT,"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id...",23000077,SLICK BOOTS
3,16000001,COLT,"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id...",23000138,MAGNUM SPECIAL
4,16000002,BULL,"[{'id': 23000272, 'name': 'T-BONE INJECTOR'}, ...",23000078,BERSERKER
5,16000002,BULL,"[{'id': 23000272, 'name': 'T-BONE INJECTOR'}, ...",23000137,TOUGH GUY
6,16000003,BROCK,"[{'id': 23000245, 'name': 'ROCKET LACES'}, {'i...",23000079,MORE ROCKETS!
7,16000003,BROCK,"[{'id': 23000245, 'name': 'ROCKET LACES'}, {'i...",23000150,ROCKET NO. 4
8,16000004,RICO,"[{'id': 23000246, 'name': 'MULTIBALL LAUNCHER'...",23000080,SUPER BOUNCY
9,16000004,RICO,"[{'id': 23000246, 'name': 'MULTIBALL LAUNCHER'...",23000156,ROBO RETREAT

In [83]:
# rename id
brawlers_expanded_clean.columns = [
    'brawler_id' if i == 0 else 'starPowers_id' if col == 'id' and i > 0 else col
    for i, col in enumerate(brawlers_expanded_clean.columns)
]
brawlers_expanded_clean.head(10)

,brawler_id,name,gadgets,starPowers_id,name
0,16000000,SHELLY,"[{'id': 23000255, 'name': 'FAST FORWARD'}, {'i...",23000076,SHELL SHOCK
1,16000000,SHELLY,"[{'id': 23000255, 'name': 'FAST FORWARD'}, {'i...",23000135,BAND-AID
2,16000001,COLT,"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id...",23000077,SLICK BOOTS
3,16000001,COLT,"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id...",23000138,MAGNUM SPECIAL
4,16000002,BULL,"[{'id': 23000272, 'name': 'T-BONE INJECTOR'}, ...",23000078,BERSERKER
5,16000002,BULL,"[{'id': 23000272, 'name': 'T-BONE INJECTOR'}, ...",23000137,TOUGH GUY
6,16000003,BROCK,"[{'id': 23000245, 'name': 'ROCKET LACES'}, {'i...",23000079,MORE ROCKETS!
7,16000003,BROCK,"[{'id': 23000245, 'name': 'ROCKET LACES'}, {'i...",23000150,ROCKET NO. 4
8,16000004,RICO,"[{'id': 23000246, 'name': 'MULTIBALL LAUNCHER'...",23000080,SUPER BOUNCY
9,16000004,RICO,"[{'id': 23000246, 'name': 'MULTIBALL LAUNCHER'...",23000156,ROBO RETREAT

In [84]:
# rename name
brawlers_expanded_clean.columns = [
    'brawler_name' if i == 1 else 'starPowers_name' if col == 'name' and i > 1 else col
    for i, col in enumerate(brawlers_expanded_clean.columns)
]
brawlers_expanded_clean.head(10)

,brawler_id,brawler_name,gadgets,starPowers_id,starPowers_name
0,16000000,SHELLY,"[{'id': 23000255, 'name': 'FAST FORWARD'}, {'i...",23000076,SHELL SHOCK
1,16000000,SHELLY,"[{'id': 23000255, 'name': 'FAST FORWARD'}, {'i...",23000135,BAND-AID
2,16000001,COLT,"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id...",23000077,SLICK BOOTS
3,16000001,COLT,"[{'id': 23000273, 'name': 'SPEEDLOADER'}, {'id...",23000138,MAGNUM SPECIAL
4,16000002,BULL,"[{'id': 23000272, 'name': 'T-BONE INJECTOR'}, ...",23000078,BERSERKER
5,16000002,BULL,"[{'id': 23000272, 'name': 'T-BONE INJECTOR'}, ...",23000137,TOUGH GUY
6,16000003,BROCK,"[{'id': 23000245, 'name': 'ROCKET LACES'}, {'i...",23000079,MORE ROCKETS!
7,16000003,BROCK,"[{'id': 23000245, 'name': 'ROCKET LACES'}, {'i...",23000150,ROCKET NO. 4
8,16000004,RICO,"[{'id': 23000246, 'name': 'MULTIBALL LAUNCHER'...",23000080,SUPER BOUNCY
9,16000004,RICO,"[{'id': 23000246, 'name': 'MULTIBALL LAUNCHER'...",23000156,ROBO RETREAT

In [85]:
# Cleaning the 'gadgets' column

# 1. Parse the 'gadgets' column from string to list of dicts
brawlers_expanded_clean['gadgets'] = brawlers_expanded_clean['gadgets'].apply(ast.literal_eval)

# 2. Expand gadgets: 1 row per gadget for each brawler
brawlers_expanded_clean = brawlers_expanded_clean.explode('gadgets').reset_index(drop=True)

# 3. Normalize the 'gadgets' dictionaries into separate columns
gadgets_df = pd.json_normalize(brawlers_expanded_clean['gadgets'])

# 4. Drop the old 'gadgets' column and combine with the flattened gadget info
brawlers_expanded_clean = pd.concat([brawlers_expanded_clean.drop(columns=['gadgets']), gadgets_df], axis=1)

brawlers_expanded_clean.head(10)

,brawler_id,brawler_name,starPowers_id,starPowers_name,id,name
0,16000000,SHELLY,23000076,SHELL SHOCK,23000255,FAST FORWARD
1,16000000,SHELLY,23000076,SHELL SHOCK,23000288,CLAY PIGEONS
2,16000000,SHELLY,23000135,BAND-AID,23000255,FAST FORWARD
3,16000000,SHELLY,23000135,BAND-AID,23000288,CLAY PIGEONS
4,16000001,COLT,23000077,SLICK BOOTS,23000273,SPEEDLOADER
5,16000001,COLT,23000077,SLICK BOOTS,23000319,SILVER BULLET
6,16000001,COLT,23000138,MAGNUM SPECIAL,23000273,SPEEDLOADER
7,16000001,COLT,23000138,MAGNUM SPECIAL,23000319,SILVER BULLET
8,16000002,BULL,23000078,BERSERKER,23000272,T-BONE INJECTOR
9,16000002,BULL,23000078,BERSERKER,23000310,STOMPER

In [86]:
# rename id and name for gadgets
brawlers_expanded_clean.rename(columns={'id': 'gadgets_id', 'name': 'gadgets_name'}, inplace=True)
brawlers_expanded_clean.head(10)

,brawler_id,brawler_name,starPowers_id,starPowers_name,gadgets_id,gadgets_name
0,16000000,SHELLY,23000076,SHELL SHOCK,23000255,FAST FORWARD
1,16000000,SHELLY,23000076,SHELL SHOCK,23000288,CLAY PIGEONS
2,16000000,SHELLY,23000135,BAND-AID,23000255,FAST FORWARD
3,16000000,SHELLY,23000135,BAND-AID,23000288,CLAY PIGEONS
4,16000001,COLT,23000077,SLICK BOOTS,23000273,SPEEDLOADER
5,16000001,COLT,23000077,SLICK BOOTS,23000319,SILVER BULLET
6,16000001,COLT,23000138,MAGNUM SPECIAL,23000273,SPEEDLOADER
7,16000001,COLT,23000138,MAGNUM SPECIAL,23000319,SILVER BULLET
8,16000002,BULL,23000078,BERSERKER,23000272,T-BONE INJECTOR
9,16000002,BULL,23000078,BERSERKER,23000310,STOMPER

In [87]:
# Save cleaned brawlers DataFrame to CSV
brawlers_expanded_clean.to_csv('cleaned_brawlers.csv', index=False)

## Battle log table

In [65]:
battlelog = pd.read_csv('battlelog.csv')
battlelog

,battleTime,event_id,event_mode,event_map,battle_mode,battle_type,battle_rank,battle_trophyChange,battle_teams,battle_result,...,player_tag,battle_bigBrawler_tag,battle_bigBrawler_name,battle_bigBrawler_brawler_id,battle_bigBrawler_brawler_name,battle_bigBrawler_brawler_power,battle_bigBrawler_brawler_trophies,battle_level_name,battle_level_id,battle_starPlayer
0,20250405T130145.000Z,15000955,trioShowdown,Cavern Churn,duoShowdown,ranked,4.0,-4.0,"[[{'tag': '#2R208RV9JY', 'name': 'momos', 'bra...",NaN,...,#9ULJPY8LV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250405T125746.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,"[[{'tag': '#C9YQYQJ8Y', 'name': '밤양갱', 'brawle...",defeat,...,#9ULJPY8LV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250405T125552.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-2.0,"[[{'tag': '#2RJCU9082Y', 'name': 'sigma', 'bra...",defeat,...,#9ULJPY8LV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20250405T125406.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,"[[{'tag': '#2RJCU9082Y', 'name': 'sigma', 'bra...",defeat,...,#9ULJPY8LV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250405T125258.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,"[[{'tag': '#2RL8CRLY9G', 'name': '番仔', 'brawle...",defeat,...,#9ULJPY8LV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,20241221T105306.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,-2.0,"[[{'tag': '#28JLR2V9', 'name': '睡觉中z', 'brawle...",NaN,...,#YOR2CO2R2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,20241221T104918.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,11.0,"[[{'tag': '#9CLLQCJVU', 'name': '🪄BlͥocͣkͫJR3'...",NaN,...,#YOR2CO2R2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,20241221T104613.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,8.0,"[[{'tag': '#88RRV8QLU', 'name': '왓 클 리', 'braw...",NaN,...,#YOR2CO2R2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,20241221T104352.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,7.0,"[[{'tag': '#GQ00VRYG8', 'name': 'りつりつ', 'brawl...",NaN,...,#YOR2CO2R2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,20241219T045654.000Z,15000440,knockout,Flaring Phoenix,knockout,ranked,NaN,-2.0,"[[{'tag': '#20GQQVP20', 'name': '라이쿠스', 'brawl...",defeat,...,#YOR2CO2R2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
# editing player_tag from O to 0
battlelog['player_tag'] = battlelog['player_tag'].replace('O', '0', regex=True)
battlelog['player_tag'].unique()

array(['#9ULJPY8LV', '#GYVL22U2V', '#LGLJCPVYG', '#PG2CCG89U',
       '#RPGJRPLP', '#GV0VYGP0', '#9U2JV20RP', '#9VY09LP0', '#VY089R8P',
       '#Y0R2C02R2'], dtype=object)

In [67]:
# Only apply ast.literal_eval if it's a string (to skip NaNs or already-parsed lists)
def safe_eval(x):
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except:
            return np.nan
    return x

# Apply safe_eval
battlelog['battle_teams'] = battlelog['battle_teams'].apply(safe_eval)

# Now define the function to extract brawler ID
def get_brawler_id(battle_teams, player_tag):
    if not isinstance(battle_teams, list):  # skip NaNs or bad data
        return np.nan
    for team in battle_teams:
        for player in team:
            if player.get('tag') == player_tag:
                return player.get('brawler', {}).get('id')
    return np.nan

In [68]:
# Apply to the DataFrame, create new column 'brawler_id_used'
battlelog['brawler_id_used'] = battlelog.apply(
    lambda row: get_brawler_id(row['battle_teams'], row['player_tag']), axis=1
)

In [49]:
battlelog

,battleTime,event_id,event_mode,event_map,battle_mode,battle_type,battle_rank,battle_trophyChange,battle_teams,battle_result,...,battle_bigBrawler_tag,battle_bigBrawler_name,battle_bigBrawler_brawler_id,battle_bigBrawler_brawler_name,battle_bigBrawler_brawler_power,battle_bigBrawler_brawler_trophies,battle_level_name,battle_level_id,battle_starPlayer,brawler_id_used
0,20250405T130145.000Z,15000955,trioShowdown,Cavern Churn,duoShowdown,ranked,4.0,-4.0,"[[{'tag': '#2R208RV9JY', 'name': 'momos', 'bra...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000043.0
1,20250405T125746.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,"[[{'tag': '#C9YQYQJ8Y', 'name': '밤양갱', 'brawle...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000018.0
2,20250405T125552.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-2.0,"[[{'tag': '#2RJCU9082Y', 'name': 'sigma', 'bra...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000019.0
3,20250405T125406.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,"[[{'tag': '#2RJCU9082Y', 'name': 'sigma', 'bra...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000014.0
4,20250405T125258.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,"[[{'tag': '#2RL8CRLY9G', 'name': '番仔', 'brawle...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,20241221T105306.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,-2.0,"[[{'tag': '#28JLR2V9', 'name': '睡觉中z', 'brawle...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,20241221T104918.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,11.0,"[[{'tag': '#9CLLQCJVU', 'name': '🪄BlͥocͣkͫJR3'...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,20241221T104613.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,8.0,"[[{'tag': '#88RRV8QLU', 'name': '왓 클 리', 'braw...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,20241221T104352.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,7.0,"[[{'tag': '#GQ00VRYG8', 'name': 'りつりつ', 'brawl...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,20241219T045654.000Z,15000440,knockout,Flaring Phoenix,knockout,ranked,NaN,-2.0,"[[{'tag': '#20GQQVP20', 'name': '라이쿠스', 'brawl...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
# Do the same for 'battle_players' column
# Safe evaluation again in case it's stored as a string
def safe_eval(x):
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except:
            return np.nan
    return x

# Apply it to battle_players
battlelog['battle_players'] = battlelog['battle_players'].apply(safe_eval)

# Function to extract brawler_id from battle_players
def get_brawler_id_2(players, player_tag):
    if not isinstance(players, list):
        return np.nan
    for player in players:
        if player.get('tag') == player_tag:
            return player.get('brawler', {}).get('id')
    return np.nan

# Apply to the DataFrame
battlelog['brawler_id_used_2'] = battlelog.apply(
    lambda row:get_brawler_id_2(row['battle_players'], row['player_tag']), axis=1
)

In [70]:
battlelog

,battleTime,event_id,event_mode,event_map,battle_mode,battle_type,battle_rank,battle_trophyChange,battle_teams,battle_result,...,battle_bigBrawler_name,battle_bigBrawler_brawler_id,battle_bigBrawler_brawler_name,battle_bigBrawler_brawler_power,battle_bigBrawler_brawler_trophies,battle_level_name,battle_level_id,battle_starPlayer,brawler_id_used,brawler_id_used_2
0,20250405T130145.000Z,15000955,trioShowdown,Cavern Churn,duoShowdown,ranked,4.0,-4.0,"[[{'tag': '#2R208RV9JY', 'name': 'momos', 'bra...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000043.0,NaN
1,20250405T125746.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,"[[{'tag': '#C9YQYQJ8Y', 'name': '밤양갱', 'brawle...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000018.0,NaN
2,20250405T125552.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-2.0,"[[{'tag': '#2RJCU9082Y', 'name': 'sigma', 'bra...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000019.0,NaN
3,20250405T125406.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,"[[{'tag': '#2RJCU9082Y', 'name': 'sigma', 'bra...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000014.0,NaN
4,20250405T125258.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,"[[{'tag': '#2RL8CRLY9G', 'name': '番仔', 'brawle...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000045.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,20241221T105306.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,-2.0,"[[{'tag': '#28JLR2V9', 'name': '睡觉中z', 'brawle...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000007.0,NaN
246,20241221T104918.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,11.0,"[[{'tag': '#9CLLQCJVU', 'name': '🪄BlͥocͣkͫJR3'...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000007.0,NaN
247,20241221T104613.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,8.0,"[[{'tag': '#88RRV8QLU', 'name': '왓 클 리', 'braw...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000007.0,NaN
248,20241221T104352.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,7.0,"[[{'tag': '#GQ00VRYG8', 'name': 'りつりつ', 'brawl...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000007.0,NaN
249,20241219T045654.000Z,15000440,knockout,Flaring Phoenix,knockout,ranked,NaN,-2.0,"[[{'tag': '#20GQQVP20', 'name': '라이쿠스', 'brawl...",defeat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000078.0,NaN

In [71]:
# Remove unneccessary columns
battlelog.drop(columns=['battle_teams', 'battle_players', 'battle_bigBrawler_tag', 'battle_bigBrawler_name', 
                        'battle_bigBrawler_brawler_id', 'battle_bigBrawler_brawler_name', 'battle_bigBrawler_brawler_power',
                        'battle_bigBrawler_brawler_trophies','battle_level_name', 'battle_level_id', 'battle_starPlayer'], 
               inplace=True)

battlelog.head(10)

,battleTime,event_id,event_mode,event_map,battle_mode,battle_type,battle_rank,battle_trophyChange,battle_result,battle_duration,battle_starPlayer_tag,battle_starPlayer_name,battle_starPlayer_brawler_id,battle_starPlayer_brawler_name,battle_starPlayer_brawler_power,battle_starPlayer_brawler_trophies,player_tag,brawler_id_used,brawler_id_used_2
0,20250405T130145.000Z,15000955,trioShowdown,Cavern Churn,duoShowdown,ranked,4.0,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#9ULJPY8LV,16000043.0,NaN
1,20250405T125746.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,defeat,28.0,#LVPJRVJPC,けんけん,16000004.0,RICO,8.0,408.0,#9ULJPY8LV,16000018.0,NaN
2,20250405T125552.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-2.0,defeat,41.0,#2RUVQ2VVY2,CR7,16000043.0,EDGAR,11.0,236.0,#9ULJPY8LV,16000019.0,NaN
3,20250405T125406.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,defeat,24.0,#Q9V98QGQ8,(⁠｡⁠ﾉ⁠ω⁠＼⁠｡⁠)嗨~,16000085.0,KENJI,10.0,470.0,#9ULJPY8LV,16000014.0,NaN
4,20250405T125258.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,defeat,49.0,#2Y2VC9CCR,嘿！空武發,16000041.0,LOU,7.0,167.0,#9ULJPY8LV,16000045.0,NaN
5,20250405T125037.000Z,15000926,hotZone,Bejeweled,hotZone,ranked,NaN,-2.0,defeat,86.0,#YYV2PUC2Q,❄️Bé Nguyên❄️,16000063.0,CHESTER,10.0,333.0,#9ULJPY8LV,16000006.0,NaN
6,20250405T124744.000Z,15000926,hotZone,Bejeweled,hotZone,ranked,NaN,-2.0,defeat,75.0,#Q9G8J992,🌵🐖🌵,16000091.0,LUMI,11.0,190.0,#9ULJPY8LV,16000022.0,NaN
7,20250405T124424.000Z,15000118,brawlBall,Pinball Dreams,brawlBall,ranked,NaN,-2.0,defeat,57.0,#2QJRVLGJC9,Chun_Hei,16000011.0,MORTIS,7.0,286.0,#9ULJPY8LV,16000030.0,NaN
8,20250405T124214.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,defeat,37.0,#V9QU9L8PQ,メロン,16000028.0,SANDY,9.0,104.0,#9ULJPY8LV,16000011.0,NaN
9,20250405T123846.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,9.0,victory,32.0,#9ULJPY8LV,CYX,16000011.0,MORTIS,11.0,91.0,#9ULJPY8LV,16000011.0,NaN

In [72]:
# combine brawler_id_used and brawler_id_used_2 columns
battlelog['brawler_id_combined'] = battlelog['brawler_id_used'].fillna(battlelog['brawler_id_used_2'])
battlelog

,battleTime,event_id,event_mode,event_map,battle_mode,battle_type,battle_rank,battle_trophyChange,battle_result,battle_duration,battle_starPlayer_tag,battle_starPlayer_name,battle_starPlayer_brawler_id,battle_starPlayer_brawler_name,battle_starPlayer_brawler_power,battle_starPlayer_brawler_trophies,player_tag,brawler_id_used,brawler_id_used_2,brawler_id_combined
0,20250405T130145.000Z,15000955,trioShowdown,Cavern Churn,duoShowdown,ranked,4.0,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#9ULJPY8LV,16000043.0,NaN,16000043.0
1,20250405T125746.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,defeat,28.0,#LVPJRVJPC,けんけん,16000004.0,RICO,8.0,408.0,#9ULJPY8LV,16000018.0,NaN,16000018.0
2,20250405T125552.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-2.0,defeat,41.0,#2RUVQ2VVY2,CR7,16000043.0,EDGAR,11.0,236.0,#9ULJPY8LV,16000019.0,NaN,16000019.0
3,20250405T125406.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,defeat,24.0,#Q9V98QGQ8,(⁠｡⁠ﾉ⁠ω⁠＼⁠｡⁠)嗨~,16000085.0,KENJI,10.0,470.0,#9ULJPY8LV,16000014.0,NaN,16000014.0
4,20250405T125258.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,defeat,49.0,#2Y2VC9CCR,嘿！空武發,16000041.0,LOU,7.0,167.0,#9ULJPY8LV,16000045.0,NaN,16000045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,20241221T105306.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#Y0R2C02R2,16000007.0,NaN,16000007.0
246,20241221T104918.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#Y0R2C02R2,16000007.0,NaN,16000007.0
247,20241221T104613.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#Y0R2C02R2,16000007.0,NaN,16000007.0
248,20241221T104352.000Z,15000431,duoShowdown,Dried Up River,duoShowdown,ranked,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#Y0R2C02R2,16000007.0,NaN,16000007.0
249,20241219T045654.000Z,15000440,knockout,Flaring Phoenix,knockout,ranked,NaN,-2.0,defeat,123.0,#GL8P8PLRL,람다,16000088.0,NaN,11.0,722.0,#Y0R2C02R2,16000078.0,NaN,16000078.0

In [73]:
battlelog.drop(columns=['brawler_id_used', 'brawler_id_used_2'], inplace=True)
battlelog.head(10)

,battleTime,event_id,event_mode,event_map,battle_mode,battle_type,battle_rank,battle_trophyChange,battle_result,battle_duration,battle_starPlayer_tag,battle_starPlayer_name,battle_starPlayer_brawler_id,battle_starPlayer_brawler_name,battle_starPlayer_brawler_power,battle_starPlayer_brawler_trophies,player_tag,brawler_id_combined
0,20250405T130145.000Z,15000955,trioShowdown,Cavern Churn,duoShowdown,ranked,4.0,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#9ULJPY8LV,16000043.0
1,20250405T125746.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,defeat,28.0,#LVPJRVJPC,けんけん,16000004.0,RICO,8.0,408.0,#9ULJPY8LV,16000018.0
2,20250405T125552.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-2.0,defeat,41.0,#2RUVQ2VVY2,CR7,16000043.0,EDGAR,11.0,236.0,#9ULJPY8LV,16000019.0
3,20250405T125406.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-3.0,defeat,24.0,#Q9V98QGQ8,(⁠｡⁠ﾉ⁠ω⁠＼⁠｡⁠)嗨~,16000085.0,KENJI,10.0,470.0,#9ULJPY8LV,16000014.0
4,20250405T125258.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,defeat,49.0,#2Y2VC9CCR,嘿！空武發,16000041.0,LOU,7.0,167.0,#9ULJPY8LV,16000045.0
5,20250405T125037.000Z,15000926,hotZone,Bejeweled,hotZone,ranked,NaN,-2.0,defeat,86.0,#YYV2PUC2Q,❄️Bé Nguyên❄️,16000063.0,CHESTER,10.0,333.0,#9ULJPY8LV,16000006.0
6,20250405T124744.000Z,15000926,hotZone,Bejeweled,hotZone,ranked,NaN,-2.0,defeat,75.0,#Q9G8J992,🌵🐖🌵,16000091.0,LUMI,11.0,190.0,#9ULJPY8LV,16000022.0
7,20250405T124424.000Z,15000118,brawlBall,Pinball Dreams,brawlBall,ranked,NaN,-2.0,defeat,57.0,#2QJRVLGJC9,Chun_Hei,16000011.0,MORTIS,7.0,286.0,#9ULJPY8LV,16000030.0
8,20250405T124214.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,-1.0,defeat,37.0,#V9QU9L8PQ,メロン,16000028.0,SANDY,9.0,104.0,#9ULJPY8LV,16000011.0
9,20250405T123846.000Z,15000679,knockout,Close Quarters,knockout,ranked,NaN,9.0,victory,32.0,#9ULJPY8LV,CYX,16000011.0,MORTIS,11.0,91.0,#9ULJPY8LV,16000011.0

In [74]:
# rename 'brawler_id_combined' to 'brawler_id_used'
battlelog.rename(columns={'brawler_id_combined': 'brawler_id_used'}, inplace=True)

In [75]:
# Save cleaned battlelog DataFrame to CSV
battlelog.to_csv('cleaned_battlelog.csv', index=False)